# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebcf3bc82d613e0f613a101bdf287d32f35c446a3d8db7f8327e023863c15031d8ec1315b426b32105ccb3d719a30e3ed7d375a09bd1e57b60b1e92520f2300e

test:
  secret_key_base: 76d7f913d2d1472721d8516b5e18ad85ef99c984ddb24a5ace6eaf249a2bd87e774df9eab3a63dca8e3b2bd0045217b8d1d495f8fe7d053a70a53c35e04bf713

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
